[project]
name = "poor_mans_terraform"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "docker>=7.1.0",
    "fastapi>=0.136.1",
    "loguru>=0.7.3",
    "tomli>=2.4.1",
    "uvicorn>=0.46.0",
]
[project.scripts]
poor_mans_terraform = "poor_mans_terraform.main:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
